name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitTools
      - uses: GitTools/actions@v0.9.13
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Determine Version
        uses: GitTools/actions/execute@v0.9.13
        with:
          useConfigFile: true
